### ISSUE TITLE
Request for additional release artifacts: checker-qual-sources, dataflow-errorprone*

### ISSUE THREAD

**Issue by cpovirk** [eisop/checker-framework#197]
Our internal process expects:
- checker-qual-sources.jar
- dataflow-errorprone.jar and dataflow-errorprone-sources.jar

The former is straightforward to generate from the included checker-source.jar.

For the latter, I've grabbed the typetools versions for now, but that sounds like probably not a good long-term solution.

Is it possible to include these in the generated release zip or as separate artifacts? I could probably also reasonably generate them myself, especially if you know offhand what commands I'd need to run. (It wasn't obvious to me from skimming https://rawgit.com/typetools/checker-framework/master/docs/developer/release/README-release-process.html)

**Comment by wmdietl** [comment]
I release the same artifacts as typetools, but in the `io.github.eisop` group: https://search.maven.org/search?q=g:io.github.eisop

If you want to build these artifacts yourself, after `./gradlew assemble` you'll find them, e.g.

````
./dataflow/build/libs/dataflow-errorprone-3.21.3-javadoc.jar
./dataflow/build/libs/dataflow-errorprone-3.21.3-sources.jar
./dataflow/build/libs/dataflow-errorprone-3.21.3.jar
````

I don't think typetools includes these artifacts in the github release. I assume you picked those artifacts from Maven Central and just need to use `io.github.eisop` artifacts instead.

Is there anything I'm missing?

**Comment by cpovirk** [comment]
Oh, thanks! I had somehow just been pulling eisop releases from https://github.com/eisop/checker-framework/releases/tag/checker-framework-3.21.2-eisop1, even as we pulled typetool releases from Maven Central. I should just be able to pull eisop from Maven Central, too, as you say.
