### ISSUE TITLE
error: AsSuperVisitor: type is not an erased subtype of supertype after version 3.21.3

### ISSUE THREAD

**Issue by al3xliu** [eisop/checker-framework#400]
Here is the test case:
```
class AnoymousAndInnerClass {
    class MyInnerClass {
        public MyInnerClass() {}

        public MyInnerClass(String s) {}

        public MyInnerClass(int... i) {}
    }

}

class Top {
    void test(AnoymousAndInnerClass outer) {
        outer.new MyInnerClass(1, 2, 3){};

    }
}
```

As far as I know, this issue only happens: 1. varargs 2.anonymous class

**Comment by wmdietl** [comment]
Thanks! You can slightly simplify it to:

````java
class AnoymousAndInnerClass {
    class MyInnerClass {
        public MyInnerClass(int... i) {}
    }
}

class Top {
    void test(AnoymousAndInnerClass outer) {
        outer.new MyInnerClass(1, 2, 3) {};
    }
}
````

This variant, without varargs, crashes for a different reason:

````java
class AnoymousAndInnerClass {
    class MyInnerClass {
        public MyInnerClass(int i) {}
    }
}

class Top {
    void test(AnoymousAndInnerClass outer) {
        outer.new MyInnerClass(1) {};
    }
}
````

What is common with both is that if method `test` is directly in `AnoymousAndInnerClass ` it does not crash.

So the culprit is the interaction between the extra parameter for inner classes and the extra parameter for an anonymous classes.

**Comment by AndrewShf** [comment]
> 
> As far as I know, this issue only happens: 1. varargs 2.anonymous class

Can you share the command for triggering this bug. I use signedness and nullness checker for these testcases, but cannot produce an error.

**Comment by al3xliu** [comment]
> > As far as I know, this issue only happens: 1. varargs 2.anonymous class
> 
> @al3xliu Can you share the command for triggering this bug? I use signedness and nullness checker for these testcases, but cannot produce an exception or error.

@AndrewShf Thanks! To reproduce the error, run `./checker/bin/javac -cp ./checker/dist/checker.jar:framework/build/classes/java/test  -processor org.checkerframework.framework.testchecker.h1h2checker.H1H2Checker -AcheckEnclosingExpr   <Your-Source-File>`.
