### ISSUE TITLE
Improve cleaning the project

### ISSUE THREAD

**Issue by wmdietl** [eisop/checker-framework#413]
Build the project with `./gradlew assemble`.
Then, after running `./gradlew clean`, there are still many build artifacts lying around, e.g. nearly 2000 `.class` files and javadoc HTML files.
If there is a different task to run to clean all files, document it. (I tried `cleanTest` and `cleanBuild` and they don't clean these files.)
If no such task exists, improve the `clean` task.

Note that there are a few test tasks that use Makefiles. Improve those by including a `clean` target and make sure these are actually run.

**Comment by wmdietl** [comment]
@Ao-senXiong Running `./gradlew clean` now fails with errors... can you please fix this?
We never run the clean target in CI... so maybe we should add a test that that target actually works.
In https://github.com/eisop/checker-framework/pull/502#discussion_r1737274406 you said you tested that change, which clearly isn't the case...

**Comment by Ao-senXiong** [comment]
> @Ao-senXiong Running `./gradlew clean` now fails with errors... can you please fix this? We never run the clean target in CI... so maybe we should add a test that that target actually works. In [#502 (comment)](https://github.com/eisop/checker-framework/pull/502#discussion_r1737274406) you said you tested that change, which clearly isn't the case...

@wmdietl What command do you use for running the test?

I just tried again with `./gradlew test` and `./gradlew clean` resulting failure. It seems either nullnessextratest did not run or `./gradlew test` clean the generated files itself.

**Comment by Ao-senXiong** [comment]
While https://github.com/eisop/checker-framework/pull/502#discussion_r1737274406 these combinations works fine.

**Comment by wmdietl** [comment]
> > @Ao-senXiong Running `./gradlew clean` now fails with errors... can you please fix this? We never run the clean target in CI... so maybe we should add a test that that target actually works. In [#502 (comment)](https://github.com/eisop/checker-framework/pull/502#discussion_r1737274406) you said you tested that change, which clearly isn't the case...
> 
> @wmdietl What command do you use for running the test?
> 
> I just tried again with `./gradlew test` and `./gradlew clean` resulting failure. It seems either nullnessextratest did not run or `./gradlew test` clean the generated files itself.

I'm not sure what you're trying to say... Can you just try running it twice: `./gradlew clean; ./gradlew clean` and the second invocation will cause errors. This might happen, e.g. after just building the project, without running tests, or running only some of the tests. Cleaning the project should always work, regardless of whether tests were run or not.
For `rm` invocations in Makefiles, try adding `-` in front of the line (after the tab) to ignore errors.
