### ISSUE TITLE
Nullness status of `MonotonicNonNull fields 

### ISSUE THREAD

**Issue by ky-gog** [eisop/checker-framework#770]
Thanks for submitting an issue.
As explained in the instructions for submitting an issue at https://eisop.github.io/cf/manual/#reporting-bugs, please include four pieces of information:
 * commands (that can be cut-and-pasted into a command shell),
 * inputs,
 * outputs, and
 * expectation.

**Comment by wmdietl** [comment]
I think this was a pre-cursor to #771.
