### ISSUE TITLE
Refine installation instructions for gradle

### ISSUE THREAD

**Issue by koppor** [eisop/checker-framework#785]
Currently, the documentation links to the [checker gradle plugin](https://github.com/kelloggm/checkerframework-gradle-plugin?tab=readme-ov-file#gradle-checker-framework-plugin) to use the checker-framework. However, the plugin uses the "upstream" checker and not this repository. 

I wished, there was a step-by-step howto to use this project to work with `jspecify` `@NonNull` annotations 😅.

**Comment by wmdietl** [comment]
Thanks for the report!
It is easy to use the Checker Gradle plug-in with EISOP, but, as you note, we need to improve the documentation.
As an example, you can look [here](https://github.com/eisop/checker-framework/blob/481040f5af69012d3b410e1844f31d84fff7b7c4/docs/examples/errorprone/build.gradle#L19).
