### ISSUE TITLE
Dependencies between test scripts

### ISSUE THREAD

**Issue by wmdietl** [eisop/checker-framework#977]
eisop/jdk split invocation of test scripts into parts: https://github.com/eisop/jdk/pull/97/files#diff-7915b9b726a397ae7ba6af7b9703633d21c031ebf21682f3ee7e6a4ec52837a5L126

That resulted in the following CI error:

````
make -C issue618
make[1]: Entering directory '/__w/1/checker-framework/checker/tests/command-line/issue618'
/__w/1/checker-framework/checker/bin/javac -AnoJreVersionCheck -processor regex,org.checkerframework.checker.tainting.TaintingChecker TwoCheckers.java > out.txt 2>&1
diff -u expected.txt out.txt
--- expected.txt	2024-11-13 02:56:37.535863130 +0000
+++ out.txt	2024-11-13 03:19:26.664848880 +0000
@@ -1,6 +1 @@
-TwoCheckers.java:28: error: [argument.type.incompatible] incompatible argument for parameter b of TwoCheckers.requiresUntainted.
-        requiresUntainted(a);
-                          ^
-  found   : @Tainted String
-  required: @Untainted String
-1 error
+Error: Unable to access jarfile /__w/1/checker-framework/checker/bin/../dist/checker.jar
make[1]: Leaving directory '/__w/1/checker-framework/checker/tests/command-line/issue618'
make: Leaving directory '/__w/1/checker-framework/checker/tests/command-line'
````

That looked like the dependencies for `command-line` were not fulfilled.
#975 tried using `doLast`, but that didn't fix the issue.
Running all tests together fixed the issue.

We should figure out why the test scripts can't run separately and fix whatever dependency issue seems to exist here.

**Comment by Ao-senXiong** [comment]
sometimes ago, I had `checker.jar` missing when I did `./gradlew clean` and `./gradlew assembleforjavac` before.

**Comment by wmdietl** [comment]
#981 sounds like the same issue and has concrete steps to reproduce.
